#!/usr/bin/env python3
"""Validate the Goal Learning OS skill package."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIRED_FILES = [
    "SKILL.md",
    "agents/openai.yaml",
    "references/repository-protocol.md",
    "references/learning-models.md",
    "references/expert-room.md",
    "references/source-policy.md",
    "references/evaluation-rubric.md",
    "scripts/check_learning_repo.py",
    "test-prompts.json",
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def check_frontmatter(skill_text: str) -> list[str]:
    issues: list[str] = []
    if not skill_text.startswith("---\n"):
        return ["SKILL.md missing YAML frontmatter"]
    match = re.match(r"---\n(.*?)\n---", skill_text, flags=re.DOTALL)
    if not match:
        return ["SKILL.md frontmatter is not closed"]
    frontmatter = match.group(1)
    for key in ["name:", "description:"]:
        if key not in frontmatter:
            issues.append(f"SKILL.md frontmatter missing {key}")
    if "name: goal-learning-os" not in frontmatter:
        issues.append("SKILL.md name must be goal-learning-os")
    return issues


def check_references_linked(skill_text: str) -> list[str]:
    issues: list[str] = []
    for path in sorted((ROOT / "references").glob("*.md")):
        rel = path.relative_to(ROOT).as_posix()
        if rel not in skill_text:
            issues.append(f"Reference not linked from SKILL.md: {rel}")
    return issues


def check_json() -> list[str]:
    path = ROOT / "test-prompts.json"
    try:
        prompts = json.loads(read_text(path))
    except json.JSONDecodeError as exc:
        return [f"Invalid test-prompts.json: {exc}"]
    if not isinstance(prompts, list) or not prompts:
        return ["test-prompts.json must contain a non-empty list"]
    issues: list[str] = []
    for idx, item in enumerate(prompts, start=1):
        if not isinstance(item, dict):
            issues.append(f"Prompt {idx} must be an object")
            continue
        for key in ["id", "prompt", "expected"]:
            if not item.get(key):
                issues.append(f"Prompt {idx} missing {key}")
    return issues


def check_no_generated_cache() -> list[str]:
    issues: list[str] = []
    for path in ROOT.rglob("__pycache__"):
        issues.append(f"Generated cache directory found: {path.relative_to(ROOT)}")
    for path in ROOT.rglob("*.pyc"):
        issues.append(f"Generated bytecode found: {path.relative_to(ROOT)}")
    return issues


def main() -> int:
    issues: list[str] = []
    for rel in REQUIRED_FILES:
        path = ROOT / rel
        if not path.is_file():
            issues.append(f"Missing required file: {rel}")
        elif path.stat().st_size == 0:
            issues.append(f"Empty required file: {rel}")

    skill_path = ROOT / "SKILL.md"
    if skill_path.is_file():
        skill_text = read_text(skill_path)
        issues.extend(check_frontmatter(skill_text))
        issues.extend(check_references_linked(skill_text))

    issues.extend(check_json())
    issues.extend(check_no_generated_cache())

    if issues:
        print("Skill package check failed:")
        for issue in issues:
            print(f"- {issue}")
        return 1
    print("Skill package check passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
